ALTER TABLE Fournisseurs 
ADD CONSTRAINT PK_Fournisseurs 
PRIMARY KEY (NO_FOURNISSEUR);

ALTER TABLE Stock_Europe_Du_Nord 
ADD CONSTRAINT PK_Stock_Europe_Du_Nord  
PRIMARY KEY (REF_PRODUIT, PAYS);


ALTER TABLE Stock_Autres
ADD CONSTRAINT PK_Stock_Autres  
PRIMARY KEY (REF_PRODUIT, PAYS);



ALTER TABLE Clients
ADD CONSTRAINT PK_Clients 
PRIMARY KEY (CODE_CLIENT);

ALTER TABLE Commandes
ADD CONSTRAINT PK_Commandes 
PRIMARY KEY ((NO_COMMANDE);


ALTER TABLE DETAILS_COMMANDES
ADD CONSTRAINT PK_DETAILS_COMMANDES 
PRIMARY KEY (NO_COMMANDE, REF_PRODUIT);

ADD TABLE STOCK 
ADD CONSTRAINT FK_STOCK_PRODUITS
FOREIGN KEY (REF_PRODUIT)
REFERENCES PRODUITS  (REF_PRODUIT).
 
CREATE OR REPLACE FK_EMPLOYES
BEFORE INSERT OR UPDATE ON Commandes
FOR EACH ROW 
DECLARE 
   CURSOR Curs_NO_EMPLOYE IS 
   SELECT NO_EMPLOYE
   FROM 
