// DROP DATABASE LINK L_DB11;
// DROP DATABASE LINK L_DB14;

CREATE DATABASE LINK L_Central
CONNECT TO fkilic IDENTIFIED BY "x"
USING 'DB11';

CREATE DATABASE LINK L_Ameriques
CONNECT TO fkilic IDENTIFIED BY "x"
USING 'DB14';