GRANT SELECT, UPDATE, INSERT, DELETE ON Fournisseurs TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Clients_Europe_Du_Nord TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Clients_Autres TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Commandes_Europe_Du_Nord TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Commandes_Autres TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Details_Commandes_Europe_Du_Nord TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Details_Commandes_Autres TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Stock_Europe_Du_Nord TO mvieiraper;
GRANT SELECT, UPDATE, INSERT, DELETE ON Stock_Autres TO mvieiraper;