GRANT SELECT ON Fournisseurs TO mvieiraper;
GRANT SELECT ON Clients_Europe_Du_Nord TO mvieiraper;
GRANT SELECT ON Clients_Autres TO mvieiraper;
GRANT SELECT ON Commandes_Europe_Du_Nord TO mvieiraper;
GRANT SELECT ON Commandes_Autres TO mvieiraper;
GRANT SELECT ON Details_Commandes_Europe_Du_Nord TO mvieiraper;
GRANT SELECT ON Details_Commandes_Autres TO mvieiraper;
GRANT SELECT ON Stock_Europe_Du_Nord TO mvieiraper;
GRANT SELECT ON Stock_Autres TO mvieiraper;