DROP DATABASE LINK L_Central;
CREATE DATABASE LINK L_Central
CONNECT TO fkilic IDENTIFIED BY "x"
USING 'DB11';

DROP DATABASE LINK L_Ameriques;
CREATE DATABASE LINK L_Ameriques
CONNECT TO fkilic IDENTIFIED BY "x"
USING 'DB14';